# Generated by Django 4.1.2 on 2022-12-13 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_inicio', models.DurationField()),
                ('duracion_termino', models.DurationField()),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dia', models.CharField(max_length=20)),
                ('orden_dia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('rut_docente', models.CharField(max_length=20)),
                ('email_docente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bloque_dias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=60)),
                ('sala', models.IntegerField()),
                ('bloque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.bloques')),
                ('dia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.dias')),
            ],
        ),
    ]
